name = "fhir_r5_client_rsvp"
version = "0.9.0"

description = "r5 rsvp client layer - see https://hexdocs.pm/fhir/ "
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
fhir_r5 = { git = "https://github.com/PotatoEMR/fhir_r5", ref = "fefbeb611bf27963ac1b04b1929cb5b67e6d9679" }
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
rsvp = ">= 2.0.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
